FROM confluentinc/cp-kafka-connect:7.4.4

# Установка HDFS коннектора
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-hdfs:latest

# Установка JDBC коннектора
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.8.4

# Копирование конфигурационных файлов Hadoop
COPY config/core-site.xml /etc/hadoop/conf/
COPY config/hdfs-site.xml /etc/hadoop/conf/

# Создание директории для плагинов
RUN mkdir -p /usr/share/confluent-hub-components